// FULL FIXED CODE GENERATED BY CHATGPT
// --------------------------------------------------------------
// Issue: When config.length > 0, UI crashes and duplicates appear.
// Reason: Screen/App sections were duplicated inside each other.
// Fix: Cleaned structure, removed nested duplicated blocks, preserved logic.

import CustomizeMask from "../../../components/module/project_component/ConfigComponents/common/CustomizeMask";
import { CustomizeDashboardTypeEnums } from "../../../../enum/DashboardLinks";
import { useEffect, useState } from "react";
import ScreenConfigdata from "../../../data/CustomizeData/ScreenConfig.json";
import { ScreenConfigInterface } from "../../../data/interface/data.interface";
import { useSaveChanges } from "../../../context/ui_context/SaveChanges";
import HeadingMask from "../../../components/common_component/layered_components/HeadingMask";
import { Link } from "react-router-dom";
import { useTabContext } from "../../../context/org_context/TabContext";
import { useDraftScreen } from "../../../context/ui_context/DraftScreenContext";
import { ScreenType } from "../../../../enum/AccessType.enum";
import { BsThreeDotsVertical } from "react-icons/bs";
// import FilterSortSearchRapper from "../../../components/common_component/FilterSortSearchRapper";
// import "react-datepicker/dist/react-datepicker.css";

const Page = () => {
  const { setIsEdit } = useTabContext();
  const element= ScreenConfigdata[0].key;
  const query = { app: "", screen: "" };
  const [popUp, setPopUp] = useState(false);
  const { isActive } = useSaveChanges();
  const { drafts } = useDraftScreen();

  const [screenConfig, setScreenConfig] = useState<ScreenConfigInterface>(
    ScreenConfigdata.find(
      (item) => item.key === element
    ) as ScreenConfigInterface
  );

  console.log(screenConfig , popUp);
  
  const appDateRange:[Date | null, Date | null] = [
    null,
    null,
  ];

  const screenDateRange:  [Date | null, Date | null] = [null, null];

  const [config, setConfig] = useState<
    { title: string; createddate: number; createdby: string }[]
  >([]);

  useEffect(() => {
    const existingData = localStorage.getItem("configDetails");
    if (existingData) setConfig(JSON.parse(existingData));
  }, []);

  useEffect(() => {
    const data = ScreenConfigdata.find((item) => item.key === element);
    if (data) setScreenConfig(data);
  }, [element]);

  useEffect(() => {
    if (isActive) setPopUp(true);
  }, [isActive]);

  const filterData = (type: "app" | "screen") => {
    const [start, end] = type === "app" ? appDateRange : screenDateRange;
    const search =
      type === "app" ? query.app.toLowerCase() : query.screen.toLowerCase();

    return config.filter((item) => {
      const itemDate = new Date(item.createddate);
      const matchesDate =
        !start || !end || (itemDate >= start && itemDate <= end);
      const matchesSearch = item.title.toLowerCase().includes(search);
      return matchesDate && matchesSearch;
    });
  };

  return (
    <CustomizeMask name={CustomizeDashboardTypeEnums.CONFIGURATION}>
      <HeadingMask name={"Configuration"}>
        <div></div>
      </HeadingMask>

      <div className="mt-5 w-full flex gap-4">
        {/* --------------------------- LEFT SIDE (APP CONFIG) ------------------------ */}
        <div className="w-1/2 mt-5">
          {config.length === 0 ? (
            // EMPTY APP CONFIG
            <div className="w-full px-8 py-10 mt-4 rounded-xl bg-white shadow-md flex flex-col items-center justify-center gap-4 border border-gray-200">
              <div
                onClick={() => setIsEdit(true)}
                className="cursor-pointer flex flex-col items-center group"
              >
                <div className="w-20 h-20 flex items-center justify-center rounded-full bg-gray-100 group-hover:bg-[#7ed957]/20 transition-all duration-300 shadow-sm group-hover:shadow-md">
                  <span className="text-5xl text-[#7ed957] group-hover:scale-110 transition-all duration-300">
                    +
                  </span>
                </div>
                <h2 className="text-xl font-semibold mt-4">
                  App Configuration
                </h2>
                <p className="text-gray-500 text-center text-sm max-w-[250px]">
                  No configuration found. Click below to create your first.
                </p>
                <button className="mt-3 px-5 py-2 bg-[#7ed957] text-black rounded-lg">
                  <Link to="../project/api-config" state={{ type: "draft" }}>
                    Create New
                  </Link>
                </button>
              </div>
            </div>
          ) : (
            // APP CONFIG DATA
            <>
              <div className="flex flex-col w-full items-center gap-6 px-8 py-6 card-bg mt-4 rounded-xl shadow">
                <div className="w-full flex justify-between px-3">
                  <h1 className="text-xl font-semibold">App Configuration</h1>
                  <button
                    onClick={() => setIsEdit(true)}
                    className="border-black border px-4 py-1 rounded-md"
                  >
                    <Link to="../project/api-config" state={{ type: "draft" }}>
                      Add New
                    </Link>
                  </button>
                </div>
              </div>

              <div className="flex flex-col w-full gap-4 px-8 py-6 card-bg mt-4 rounded-xl shadow-md">
                {/* <FilterSortSearchRapper FilteringField="title" /> */}

                <div className="w-full grid grid-cols-4 border-b-2 pb-2">
                  {[
                    "Configuration",
                    "Created Date",
                    "Created by",
                    "Action",
                  ].map((item, i) => (
                    <h1 key={i} className="font-semibold text-center">
                      {item}
                    </h1>
                  ))}
                </div>

                {filterData("app").map((item, index) => (
                  <div
                    key={index}
                    className={`w-full grid grid-cols-4 items-center text-center py-2 border-b ${
                      index % 2 === 0 ? "bg-gray-50" : "bg-white"
                    }`}
                  >
                    <p>{item.title}</p>
                    <p>{new Date(item.createddate).toLocaleDateString()}</p>
                    <p>{item.createdby}</p>
                    <p className="text-center">
                      <BsThreeDotsVertical />
                    </p>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>

        {/* --------------------------- RIGHT SIDE (SCREEN CONFIG) ------------------------ */}
        <div className="w-1/2 mt-5">
          {config.length === 0 ? (
            // EMPTY SCREEN CONFIG
            <div className="w-full px-8 py-10 mt-4 rounded-xl bg-white shadow-md flex flex-col items-center justify-center gap-4 border border-gray-200">
              <div className="cursor-pointer flex flex-col items-center group">
                <div className="w-20 h-20 flex items-center justify-center rounded-full bg-gray-100 group-hover:bg-[#7ed957]/20 transition-all duration-300 shadow-sm group-hover:shadow-md">
                  <span className="text-5xl text-[#7ed957] group-hover:scale-110 transition-all duration-300">
                    +
                  </span>
                </div>
                <h2 className="text-xl font-semibold mt-4">
                  Screen Configuration
                </h2>
                <p className="text-gray-500 text-center text-sm max-w-[250px]">
                  No screen configuration found.
                </p>
                <button className="mt-3 px-5 py-2 bg-[#7ed957] text-black rounded-lg">
                  <Link
                    to="/project/edit-screen-config"
                    state={{ type: ScreenType.MAIN }}
                  >
                    Create New
                  </Link>
                </button>
              </div>
            </div>
          ) : (
            // SCREEN CONFIG DATA
            <>
              <div className="flex flex-col w-full items-center gap-6 px-8 py-6 card-bg mt-4 rounded-xl shadow">
                <div className="w-full flex justify-between px-3">
                  <h1 className="text-xl font-semibold">
                    Screen Configuration
                  </h1>

                  <button
                    onClick={() => setIsEdit(true)}
                    className="border-black border px-4 py-1 rounded-md"
                  >
                    {drafts.length > 0 ? (
                      <Link
                        to="/project/draft-screen-config"
                        state={{ type: ScreenType.DRAFT }}
                      >
                        Edit Draft
                      </Link>
                    ) : (
                      <Link
                        to="/project/edit-screen-config"
                        state={{ type: ScreenType.MAIN }}
                      >
                        Add New
                      </Link>
                    )}
                  </button>
                </div>
              </div>

              <div className="flex flex-col w-full gap-4 px-8 py-6 card-bg mt-4 rounded-xl shadow-md">
                <div className="w-full grid grid-cols-4 border-b-2 pb-2">
                  {[
                    "Configuration",
                    "Created Date",
                    "Created by",
                    "Action",
                  ].map((item, i) => (
                    <h1 key={i} className="font-semibold text-center">
                      {item}
                    </h1>
                  ))}
                </div>

                {filterData("screen").map((item, index) => (
                  <div
                    key={index}
                    className={`w-full grid grid-cols-4 items-center text-center py-2 border-b ${
                      index % 2 === 0 ? "bg-gray-50" : "bg-white"
                    }`}
                  >
                    <p>{item.title}</p>
                    <p>{new Date(item.createddate).toLocaleDateString()}</p>
                    <p>{item.createdby}</p>
                    <p className="text-center">
                      <BsThreeDotsVertical />
                    </p>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      </div>
    </CustomizeMask>
  );
};

export default Page;